apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vaultwarden-data
  namespace: vaultwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  selector:
    matchLabels:
      app: vaultwarden
  replicas: 1
  template:
    metadata:
      labels:
        app: vaultwarden
    spec:
      containers:
      - image: vaultwarden/server:1.26.0
        imagePullPolicy: IfNotPresent
        name: vaultwarden
        env:
          - name: SIGNUPS_ALLOWED
            value: "false"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /data
            name: vaultwarden-data
      volumes:
        - name: vaultwarden-data
          persistentVolumeClaim:
            claimName: vaultwarden-data
---
apiVersion: v1
kind: Service
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: vaultwarden
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bitwarden-backend
  namespace: vaultwarden
spec:
  parentRefs:
    - name: envoy-gateway
      namespace: envoy-gateway-system
  hostnames:
    - "bitwarden.aidengrossman.com"
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: vaultwarden
          port: 80
          weight: 1
      matches:
        - path:
            type: PathPrefix
            value: /
