apiVersion: v1
kind: Service
metadata:
  name: minio-expose
  labels:
    app: minio
spec:
  type: LoadBalancer
  selector:
    app: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: minio
