apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "gitlab-storage"
provisioner: linstor.csi.linbit.com
parameters:
  autoPlace: "2"
  storagePool: "ssd"
  resourceGroup: "gitlab-storage"
allowVolumeExpansion: true
reclaimPolicy: Delete
