apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agrossman154@yahoo.com 
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        cloudflare:
          email: agrossman154@yahoo.com
          apiTokenSecretRef:
            name: cloudflare-apikey-secret
            key: apikey
      selector:
        dnsNames:
          - '*.pages.aidengrossman.com'
          - 'pages.aidengrossman.com'
